DROP TABLE IF EXISTS SupplementLog;
DROP TABLE IF EXISTS ExerciseLog;
DROP TABLE IF EXISTS NutritionLog;
DROP TABLE IF EXISTS SleepLog;
DROP TABLE IF EXISTS Goal;
DROP TABLE IF EXISTS WorkoutPlan;
DROP TABLE IF EXISTS Exercise;
DROP TABLE IF EXISTS Users;
